# Generated by Django 4.2.7 on 2024-04-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_profile_image'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like_list',
            field=models.ManyToManyField(blank=True, related_name='post_like_list', to='user.user'),
        ),
    ]
