# Generated by Django 4.2.7 on 2024-04-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_knowledge_created_on_knowledge_modified_on'),
        ('post', '0002_post_like_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='knowledge',
            field=models.ManyToManyField(blank=True, related_name='post_knowledge', to='knowledge.knowledge'),
        ),
    ]
