# Generated by Django 4.2.7 on 2024-04-30 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src_code', '0001_initial'),
        ('post', '0003_post_knowledge'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='src_code',
            field=models.ManyToManyField(blank=True, related_name='post_src_code', to='src_code.srccode'),
        ),
    ]
