# Generated by Django 4.2.7 on 2024-05-09 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_src_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('1', 'Open'), ('2', 'Closed')], default='2', max_length=20),
        ),
    ]
