# Generated by Django 4.2.7 on 2024-05-20 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_post_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='knowledge',
        ),
    ]
