# Generated by Django 4.2.7 on 2024-05-31 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_remove_post_knowledge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentpost',
            name='comment_auth',
        ),
        migrations.RemoveField(
            model_name='commentpost',
            name='comment_list',
        ),
        migrations.RemoveField(
            model_name='commentpost',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='commentpost',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='commentpost',
            name='like_auth',
        ),
        migrations.RemoveField(
            model_name='commentpost',
            name='likes',
        ),
    ]
