# Generated by Django 4.2.7 on 2024-06-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_remove_post_src_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentpost',
            name='created_by_image',
            field=models.ImageField(blank=True, null=True, upload_to='user_image'),
        ),
    ]
