# Generated by Django 4.2.7 on 2024-04-20 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_fingerprint', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IPObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PublicUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='unreg_user.device')),
                ('ip_objects', models.ManyToManyField(blank=True, to='unreg_user.ipobject')),
            ],
        ),
        migrations.CreateModel(
            name='WebBrowser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_fingerprint', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReadingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remain', models.PositiveIntegerField(default=2)),
                ('current_month_access', models.PositiveIntegerField(default=0)),
                ('public_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='unreg_user.publicuser')),
                ('read_articles', models.ManyToManyField(blank=True, to='article.article')),
            ],
        ),
        migrations.AddField(
            model_name='publicuser',
            name='web_browser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unreg_user.webbrowser'),
        ),
        migrations.AddField(
            model_name='ipobject',
            name='unreg_users',
            field=models.ManyToManyField(blank=True, to='unreg_user.publicuser'),
        ),
    ]
