# Generated by Django 4.2.7 on 2024-04-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='comment_list',
            field=models.ManyToManyField(blank=True, related_name='article_comment_list', to='user.user'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_by_image',
            field=models.ImageField(blank=True, null=True, upload_to='user_image'),
        ),
    ]
