# Generated by Django 4.2.7 on 2024-05-22 15:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='like_list',
            field=models.ManyToManyField(blank=True, related_name='article_like_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
