# Generated by Django 4.2.7 on 2024-04-07 10:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0002_alter_article_comment_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='comment_auth',
            field=models.ManyToManyField(blank=True, related_name='article_auth_commenter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='like_auth',
            field=models.ManyToManyField(blank=True, related_name='article_auth_liker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_auth',
            field=models.ManyToManyField(blank=True, related_name='comment_auth_commenter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='like_auth',
            field=models.ManyToManyField(blank=True, related_name='comment_auth_liker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='comment_list',
            field=models.ManyToManyField(blank=True, related_name='article_comment_list', to='article.comment'),
        ),
    ]
