# Generated by Django 4.2.7 on 2024-04-07 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src_code', '0001_initial'),
        ('article', '0003_article_comment_auth_article_like_auth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='src_code',
            field=models.ManyToManyField(blank=True, related_name='article_src_code', to='src_code.srccode'),
        ),
    ]
