# Generated by Django 4.2.7 on 2024-05-31 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_article_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_auth',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_list',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='like_auth',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='like_list',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
    ]
