# Generated by Django 4.2.7 on 2024-06-05 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_comment_last_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='src_code',
        ),
    ]
