# Generated by Django 4.2.7 on 2024-05-09 10:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src_code', '0002_srccode_created_by_srccode_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='srccode',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
