# Generated by Django 4.2.7 on 2024-06-05 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_remove_article_src_code'),
        ('post', '0008_remove_post_src_code'),
        ('src_code', '0004_srccode_artircle_srccode_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='srccode',
            name='artircle',
        ),
        migrations.RemoveField(
            model_name='srccode',
            name='posts',
        ),
        migrations.AddField(
            model_name='srccode',
            name='article',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='article.article'),
        ),
        migrations.AddField(
            model_name='srccode',
            name='post',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='post.post'),
        ),
    ]
