# Generated by Django 4.2.7 on 2024-04-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='/media/user_profile/default.png', null=True, upload_to='user_profile'),
        ),
    ]
