# Generated by Django 4.2.7 on 2024-04-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='user_profile/default.png', null=True, upload_to='user_profile'),
        ),
    ]
