# Generated by Django 4.2.7 on 2024-06-05 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_student_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_use',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
